server:
  port: 9000

spring:
  cloud:
    stream:
      bindings:
        learning-spring-boot:
           destination: comments.new
           group: learning-spring-boot

  application:
    name: comments

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/